import { useState, type ReactNode } from 'react';
import { Navigate, Route, Routes, Link, useNavigate } from 'react-router-dom';
import { signInAnonymously, linkWithCredential, EmailAuthProvider, deleteUser } from 'firebase/auth';
import { doc, getDoc, runTransaction, serverTimestamp } from 'firebase/firestore';
import { auth, db } from './firebase';
import { aliasFor, useAuth } from './AuthContext';
import { ShieldCheck, KeyRound, LayoutDashboard, Users, Settings, LogOut } from 'lucide-react';

const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s.trim().toUpperCase())))).map(b=>b.toString(16).padStart(2,'0')).join('');
function Login(){const {login}=useAuth();const nav=useNavigate();const [u,setU]=useState('');const [p,setP]=useState('');const [e,setE]=useState('');return <AuthCard title="Welcome back" subtitle="Sign in with your Canela portal credentials."><form onSubmit={async x=>{x.preventDefault();setE('');try{await login(u,p);nav('/dashboard')}catch{setE('Invalid username or password.')}}}><label>Username<input value={u} onChange={x=>setU(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required minLength={10}/></label>{e&&<p className="error">{e}</p>}<button>Sign in</button></form><p className="muted">Have an activation code? <Link to="/activate">Activate account</Link></p></AuthCard>}
function Activate(){const nav=useNavigate();const [code,setCode]=useState('');const [u,setU]=useState('');const [p,setP]=useState('');const [e,setE]=useState('');return <AuthCard title="Activate your account" subtitle="Use the one-time code provided by an authorized administrator."><form onSubmit={async x=>{x.preventDefault();setE('');let temp=false;try{await signInAnonymously(auth);temp=true;const codeId=await hash(code);const codeRef=doc(db,'activationCodes',codeId);const preview=await getDoc(codeRef);if(!preview.exists())throw new Error('Invalid activation code.');const data=preview.data();if(data.status!=='PENDING'||data.expiresAt?.toMillis()<Date.now())throw new Error('This activation code is invalid or expired.');const credential=EmailAuthProvider.credential(aliasFor(u),p);if(!auth.currentUser)throw new Error('Activation failed.');await linkWithCredential(auth.currentUser,credential);const uid=auth.currentUser.uid;await runTransaction(db,async tx=>{const fresh=await tx.get(codeRef);if(!fresh.exists())throw new Error('Invalid activation code.');const c=fresh.data();if(c.status!=='PENDING'||c.expiresAt?.toMillis()<Date.now())throw new Error('This activation code is invalid or expired.');tx.set(doc(db,'portalAccounts',uid),{displayName:c.displayName,portalUsername:u.trim().toLowerCase(),organizationalRank:c.organizationalRank??'Staff',portalStatus:'ACTIVE',systemRoles:[],permissions:c.permissions??[],staffProfileId:c.staffProfileId,activationCodeHash:codeId,createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()});tx.set(doc(db,'portalUsernames',u.trim().toLowerCase()),{uid,createdAt:serverTimestamp()});tx.update(codeRef,{status:'USED',usedByUid:uid,usedAt:serverTimestamp()});tx.set(doc(db,'auditLogs',crypto.randomUUID()),{action:'ACCOUNT_ACTIVATED',actorUid:uid,targetUid:uid,createdAt:serverTimestamp()});});nav('/dashboard')}catch(err){if(temp&&auth.currentUser)await deleteUser(auth.currentUser).catch(()=>{});setE(err instanceof Error?err.message:'Activation failed.')}}}><label>Activation code<input value={code} onChange={x=>setCode(x.target.value)} required/></label><label>Choose username<input value={u} onChange={x=>setU(x.target.value)} pattern="[A-Za-z0-9._-]{4,24}" required/></label><label>Choose password<input type="password" value={p} onChange={x=>setP(x.target.value)} minLength={10} required/></label>{e&&<p className="error">{e}</p>}<button>Activate account</button></form><p className="muted"><Link to="/login">Return to sign in</Link></p></AuthCard>}
function AuthCard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <main className="auth"><section className="auth-card"><div className="brand-mark"><ShieldCheck/></div><p className="eyebrow">CANELA CORPORATION</p><h1>{title}</h1><p className="muted">{subtitle}</p>{children}</section></main>}
function Shell(){const {account,logout}=useAuth();return <div className="shell"><aside><div className="logo"><ShieldCheck/><span>CANELA</span></div><nav><Link to="/dashboard"><LayoutDashboard/>Dashboard</Link><span className="disabled"><Users/>Staff Directory</span>{account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')&&<Link to="/admin"><Settings/>System Admin</Link>}</nav><button className="ghost" onClick={logout}><LogOut/>Sign out</button></aside><main className="content"><header><div><p className="eyebrow">ADMINISTRATION PORTAL</p><h1>Welcome, {account?.displayName}</h1></div><span className="pill">{account?.organizationalRank}</span></header><Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="admin" element={<Admin/>}/><Route path="*" element={<Navigate to="dashboard"/>}/></Routes></main></div>}
function Dashboard(){return <><section className="hero"><div><p className="eyebrow">PHASE ONE</p><h2>Your secure workspace is ready.</h2><p>Authentication, protected routes, system roles, account states, and audit foundations are connected.</p></div><ShieldCheck/></section><div className="grid"><Card title="Account Security" value="Active" text="Cross-device username and password access"/><Card title="Portal Foundation" value="Online" text="Firebase and Firestore connected"/><Card title="Next Module" value="Staff" text="Directory and personnel operations"/></div></>}
function Card({title,value,text}:{title:string;value:string;text:string}){return <article className="card"><p>{title}</p><strong>{value}</strong><span>{text}</span></article>}
function Admin(){const {account}=useAuth();if(!account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR'))return <Navigate to="/dashboard"/>;return <section className="panel"><KeyRound/><div><h2>System Administration</h2><p>Bootstrap activation codes in Firestore now. Full code generation controls arrive with the staff-account management module.</p></div></section>}
function Protected(){const {user,account,loading}=useAuth();if(loading)return <div className="loading">Loading Canela Portal…</div>;if(!user||!account||account.portalStatus!=='ACTIVE')return <Navigate to="/login"/>;return <Shell/>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/activate" element={<Activate/>}/><Route path="/*" element={<Protected/>}/></Routes>}
