import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Navigate, Route, Routes, Link, NavLink, useNavigate } from 'react-router-dom';
import { signInAnonymously, linkWithCredential, EmailAuthProvider, deleteUser } from 'firebase/auth';
import { addDoc, collection, doc, getDoc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import { auth, db } from './firebase';
import { aliasFor, useAuth } from './AuthContext';
import type { Announcement, Department, PersonnelAction, QuotaSubmission, Rank, StaffProfile, StaffStatus } from './types';
import { ShieldCheck, KeyRound, LayoutDashboard, Users, Settings, LogOut, Building2, Award, ClipboardCheck, Megaphone, Plus, Search, ArrowRightLeft, CalendarClock, Menu, X } from 'lucide-react';

const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s.trim().toUpperCase())))).map(b=>b.toString(16).padStart(2,'0')).join('');
const fmt=(value:any)=>value?.toDate?.().toLocaleDateString()??'—';
const clean=(value:string)=>value.trim();

function useCollectionData<T>(path:string, constraints:any[]=[]){const [data,setData]=useState<T[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{const q=query(collection(db,path),...constraints);return onSnapshot(q,s=>{setData(s.docs.map(d=>({id:d.id,...d.data()} as T)));setLoading(false)},()=>setLoading(false))},[path,JSON.stringify(constraints.map((c:any)=>c?.type??''))]);return {data,loading}}

function Login(){const {login}=useAuth();const nav=useNavigate();const [u,setU]=useState('');const [p,setP]=useState('');const [e,setE]=useState('');return <AuthCard title="Welcome back" subtitle="Sign in with your Canela portal credentials."><form onSubmit={async x=>{x.preventDefault();setE('');try{await login(u,p);nav('/dashboard')}catch{setE('Invalid username or password.')}}}><label>Username<input value={u} onChange={x=>setU(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required minLength={10}/></label>{e&&<p className="error">{e}</p>}<button>Sign in</button></form><p className="muted">Have an activation code? <Link to="/activate">Activate account</Link></p></AuthCard>}
function Activate(){const nav=useNavigate();const [code,setCode]=useState('');const [u,setU]=useState('');const [p,setP]=useState('');const [e,setE]=useState('');return <AuthCard title="Activate your account" subtitle="Use the one-time code provided by an authorized administrator."><form onSubmit={async x=>{x.preventDefault();setE('');let temp=false;try{await signInAnonymously(auth);temp=true;const codeId=await hash(code);const codeRef=doc(db,'activationCodes',codeId);const preview=await getDoc(codeRef);if(!preview.exists())throw new Error('Invalid activation code.');const data=preview.data();if(data.status!=='PENDING'||data.expiresAt?.toMillis()<Date.now())throw new Error('This activation code is invalid or expired.');const credential=EmailAuthProvider.credential(aliasFor(u),p);if(!auth.currentUser)throw new Error('Activation failed.');await linkWithCredential(auth.currentUser,credential);const uid=auth.currentUser.uid;await runTransaction(db,async tx=>{const fresh=await tx.get(codeRef);if(!fresh.exists())throw new Error('Invalid activation code.');const c=fresh.data();if(c.status!=='PENDING'||c.expiresAt?.toMillis()<Date.now())throw new Error('This activation code is invalid or expired.');tx.set(doc(db,'portalAccounts',uid),{displayName:c.displayName,portalUsername:u.trim().toLowerCase(),organizationalRank:c.organizationalRank??'Staff',portalStatus:'ACTIVE',systemRoles:[],permissions:c.permissions??[],staffProfileId:c.staffProfileId,activationCodeHash:codeId,createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()});tx.set(doc(db,'portalUsernames',u.trim().toLowerCase()),{uid,createdAt:serverTimestamp()});tx.update(codeRef,{status:'USED',usedByUid:uid,usedAt:serverTimestamp()});tx.set(doc(db,'auditLogs',crypto.randomUUID()),{action:'ACCOUNT_ACTIVATED',actorUid:uid,targetUid:uid,createdAt:serverTimestamp()});});nav('/dashboard')}catch(err){if(temp&&auth.currentUser)await deleteUser(auth.currentUser).catch(()=>{});setE(err instanceof Error?err.message:'Activation failed.')}}}><label>Activation code<input value={code} onChange={x=>setCode(x.target.value)} required/></label><label>Choose username<input value={u} onChange={x=>setU(x.target.value)} pattern="[A-Za-z0-9._-]{4,24}" required/></label><label>Choose password<input type="password" value={p} onChange={x=>setP(x.target.value)} minLength={10} required/></label>{e&&<p className="error">{e}</p>}<button>Activate account</button></form><p className="muted"><Link to="/login">Return to sign in</Link></p></AuthCard>}
function AuthCard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <main className="auth"><section className="auth-card"><div className="brand-mark"><ShieldCheck/></div><p className="eyebrow">CANELA CORPORATION</p><h1>{title}</h1><p className="muted">{subtitle}</p>{children}</section></main>}

function Shell(){const {account,logout}=useAuth();const [open,setOpen]=useState(false);const admin=account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR');return <div className="shell"><aside className={open?'open':''}><div className="logo"><ShieldCheck/><span>CANELA</span><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div><nav onClick={()=>setOpen(false)}><NavLink to="/dashboard"><LayoutDashboard/>Dashboard</NavLink><NavLink to="/staff"><Users/>Staff Directory</NavLink><NavLink to="/organization"><Building2/>Organization</NavLink><NavLink to="/personnel"><ArrowRightLeft/>Personnel</NavLink><NavLink to="/quotas"><ClipboardCheck/>Quotas</NavLink><NavLink to="/announcements"><Megaphone/>Announcements</NavLink>{admin&&<NavLink to="/admin"><Settings/>System Admin</NavLink>}</nav><button className="ghost" onClick={logout}><LogOut/>Sign out</button></aside><main className="content"><header><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu/></button><div><p className="eyebrow">ADMINISTRATION PORTAL</p><h1>Welcome, {account?.displayName}</h1></div><span className="pill">{account?.organizationalRank}</span></header><Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="staff" element={<StaffDirectory/>}/><Route path="staff/:id" element={<StaffDirectory/>}/><Route path="organization" element={<Organization/>}/><Route path="personnel" element={<Personnel/>}/><Route path="quotas" element={<Quotas/>}/><Route path="announcements" element={<Announcements/>}/><Route path="admin" element={<Admin/>}/><Route path="*" element={<Navigate to="dashboard"/>}/></Routes></main></div>}

function Dashboard(){const {data:staff}=useCollectionData<StaffProfile>('staffProfiles');const {data:actions}=useCollectionData<PersonnelAction>('personnelActions');const {data:quotas}=useCollectionData<QuotaSubmission>('quotaSubmissions');const {data:ann}=useCollectionData<Announcement>('announcements');const active=staff.filter(s=>s.status==='ACTIVE').length;const pending=actions.filter(a=>a.status==='PENDING').length+quotas.filter(q=>q.status==='PENDING').length;return <><section className="hero"><div><p className="eyebrow">PHASE TWO</p><h2>Personnel operations in one connected workspace.</h2><p>Manage the staff directory, hierarchy, promotions, transfers, quotas, leave, resignations, and organization-wide announcements.</p></div><ShieldCheck/></section><div className="grid"><Card title="Active Staff" value={String(active)} text={`${staff.length} total profiles`}/><Card title="Pending Reviews" value={String(pending)} text="Personnel and quota requests"/><Card title="Announcements" value={String(ann.filter(a=>a.published).length)} text="Currently published"/></div><section className="section"><SectionTitle title="Recent personnel activity" subtitle="Latest requests and organizational changes"/><DataTable headers={['Staff','Action','Change','Status']} rows={actions.slice(0,6).map(a=>[a.staffName,a.type,`${a.fromValue??'—'} → ${a.toValue??'—'}`,<Status value={a.status}/>])}/></section></>}
function Card({title,value,text}:{title:string;value:string;text:string}){return <article className="card"><p>{title}</p><strong>{value}</strong><span>{text}</span></article>}

function StaffDirectory(){const {account}=useAuth();const {data:staff,loading}=useCollectionData<StaffProfile>('staffProfiles',[orderBy('displayName')]);const {data:ranks}=useCollectionData<Rank>('ranks');const {data:departments}=useCollectionData<Department>('departments');const [search,setSearch]=useState('');const [show,setShow]=useState(false);const filtered=useMemo(()=>staff.filter(s=>`${s.displayName} ${s.robloxUsername} ${s.robloxUserId} ${s.discordUsername} ${s.discordId}`.toLowerCase().includes(search.toLowerCase())),[staff,search]);const canManage=Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes('staff.manage'));
async function createStaff(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addDoc(collection(db,'staffProfiles'),{displayName:clean(String(f.get('displayName'))),robloxUsername:clean(String(f.get('robloxUsername'))),robloxUserId:clean(String(f.get('robloxUserId'))),discordUsername:clean(String(f.get('discordUsername'))),discordId:clean(String(f.get('discordId'))),rankId:String(f.get('rankId')),departmentId:String(f.get('departmentId')),status:'ACTIVE',quotaPoints:0,quotaTarget:Number(f.get('quotaTarget')||0),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser?.uid});setShow(false);}
return <section><SectionTitle title="Staff Directory" subtitle="One profile for every Canela staff member" action={canManage?<button onClick={()=>setShow(true)}><Plus/>Add staff member</button>:undefined}/><div className="toolbar"><label className="search"><Search/><input placeholder="Search Roblox, Discord, ID, or name" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{filtered.length} records</span></div>{loading?<Empty text="Loading staff records…"/>:<div className="staff-grid">{filtered.map(s=><article className="staff-card" key={s.id}><div className="avatar">{s.displayName.slice(0,2).toUpperCase()}</div><div><h3>{s.displayName}</h3><p>@{s.robloxUsername}</p></div><Status value={s.status}/><dl><div><dt>Rank</dt><dd>{ranks.find(r=>r.id===s.rankId)?.name??s.rankId||'Unassigned'}</dd></div><div><dt>Department</dt><dd>{departments.find(d=>d.id===s.departmentId)?.name??s.departmentId||'Unassigned'}</dd></div><div><dt>Discord</dt><dd>{s.discordUsername||'—'}</dd></div><div><dt>Quota</dt><dd>{s.quotaPoints??0} / {s.quotaTarget??0}</dd></div></dl>{canManage&&<select value={s.status} onChange={e=>updateDoc(doc(db,'staffProfiles',s.id),{status:e.target.value,updatedAt:serverTimestamp()})}>{['ACTIVE','LEAVE_OF_ABSENCE','SUSPENDED','RESIGNED','TERMINATED','FORMER_STAFF'].map(x=><option key={x}>{x}</option>)}</select>}</article>)}</div>}{show&&<Modal title="Create staff profile" close={()=>setShow(false)}><form onSubmit={createStaff} className="form-grid"><label>Display name<input name="displayName" required/></label><label>Roblox username<input name="robloxUsername" required/></label><label>Roblox User ID<input name="robloxUserId" required inputMode="numeric"/></label><label>Discord username<input name="discordUsername" required/></label><label>Discord ID<input name="discordId" required inputMode="numeric"/></label><label>Rank<select name="rankId" required><option value="">Select rank</option>{ranks.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>Department<select name="departmentId" required><option value="">Select department</option>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Quota target<input name="quotaTarget" type="number" min="0" defaultValue="0"/></label><button className="wide">Create profile</button></form></Modal>}</section>}

function Organization(){const {account}=useAuth();const {data:ranks}=useCollectionData<Rank>('ranks',[orderBy('order')]);const {data:departments}=useCollectionData<Department>('departments',[orderBy('name')]);const {data:staff}=useCollectionData<StaffProfile>('staffProfiles');const [tab,setTab]=useState<'ranks'|'departments'>('ranks');const [show,setShow]=useState(false);const canManage=Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes('organization.manage'));
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(tab==='ranks')await addDoc(collection(db,'ranks'),{name:clean(String(f.get('name'))),abbreviation:clean(String(f.get('abbreviation'))),tier:clean(String(f.get('tier'))),order:Number(f.get('order')),limit:Number(f.get('limit')||0),quotaTarget:Number(f.get('quotaTarget')||0),description:clean(String(f.get('description')||'')),createdAt:serverTimestamp()});else await addDoc(collection(db,'departments'),{name:clean(String(f.get('name'))),abbreviation:clean(String(f.get('abbreviation'))),description:clean(String(f.get('description')||'')),active:true,createdAt:serverTimestamp()});setShow(false)}
return <section><SectionTitle title="Organization" subtitle="Ranks, tiers, limits, departments, and structure" action={canManage?<button onClick={()=>setShow(true)}><Plus/>Add {tab==='ranks'?'rank':'department'}</button>:undefined}/><div className="tabs"><button className={tab==='ranks'?'selected':''} onClick={()=>setTab('ranks')}>Ranks</button><button className={tab==='departments'?'selected':''} onClick={()=>setTab('departments')}>Departments</button></div>{tab==='ranks'?<DataTable headers={['Order','Rank','Tier','Occupancy','Quota']} rows={ranks.map(r=>[r.order,`${r.name} (${r.abbreviation})`,r.tier,`${staff.filter(s=>s.rankId===r.id&&s.status==='ACTIVE').length} / ${r.limit||'∞'}`,r.quotaTarget??0])}/>:<div className="department-grid">{departments.map(d=><article className="card" key={d.id}><p>{d.abbreviation}</p><strong>{d.name}</strong><span>{staff.filter(s=>s.departmentId===d.id&&s.status==='ACTIVE').length} active members</span><small>{d.description}</small></article>)}</div>}{show&&<Modal title={`Add ${tab==='ranks'?'rank':'department'}`} close={()=>setShow(false)}><form onSubmit={create} className="form-grid"><label>Name<input name="name" required/></label><label>Abbreviation<input name="abbreviation" required/></label>{tab==='ranks'&&<><label>Tier<input name="tier" required/></label><label>Hierarchy order<input name="order" type="number" required/></label><label>Rank limit<input name="limit" type="number" min="0"/></label><label>Quota target<input name="quotaTarget" type="number" min="0"/></label></>}<label className="wide">Description<textarea name="description" rows={4}/></label><button className="wide">Save</button></form></Modal>}</section>}

function Personnel(){const {account}=useAuth();const {data:staff}=useCollectionData<StaffProfile>('staffProfiles',[orderBy('displayName')]);const {data:ranks}=useCollectionData<Rank>('ranks',[orderBy('order')]);const {data:departments}=useCollectionData<Department>('departments',[orderBy('name')]);const {data:actions}=useCollectionData<PersonnelAction>('personnelActions',[orderBy('createdAt','desc')]);const [show,setShow]=useState(false);const canApprove=Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes('personnel.approve'));
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const member=staff.find(s=>s.id===f.get('staffProfileId'));if(!member)return;const type=String(f.get('type')) as PersonnelAction['type'];await addDoc(collection(db,'personnelActions'),{staffProfileId:member.id,staffName:member.displayName,type,fromValue:String(f.get('fromValue')||''),toValue:String(f.get('toValue')||''),reason:clean(String(f.get('reason'))),status:'PENDING',requestedBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}
async function decide(action:PersonnelAction,status:'APPROVED'|'DENIED'){await runTransaction(db,async tx=>{const actionRef=doc(db,'personnelActions',action.id);tx.update(actionRef,{status,approvedBy:auth.currentUser?.uid,effectiveAt:serverTimestamp()});if(status==='APPROVED'){const patch:any={updatedAt:serverTimestamp()};if(action.type==='PROMOTION'||action.type==='DEMOTION')patch.rankId=action.toValue;if(action.type==='TRANSFER')patch.departmentId=action.toValue;if(action.type==='RESIGNATION')patch.status='RESIGNED';if(action.type==='TERMINATION')patch.status='TERMINATED';if(action.type==='STATUS_CHANGE')patch.status=action.toValue;tx.update(doc(db,'staffProfiles',action.staffProfileId),patch)}tx.set(doc(db,'auditLogs',crypto.randomUUID()),{action:`PERSONNEL_${status}`,actorUid:auth.currentUser?.uid,targetId:action.id,createdAt:serverTimestamp()})})}
return <section><SectionTitle title="Personnel Operations" subtitle="Promotions, demotions, transfers, leave, resignations, and terminations" action={<button onClick={()=>setShow(true)}><Plus/>New request</button>}/><DataTable headers={['Staff','Type','Change','Reason','Requested','Status','Review']} rows={actions.map(a=>[a.staffName,a.type,`${labelValue(a.fromValue,ranks,departments)} → ${labelValue(a.toValue,ranks,departments)}`,a.reason,fmt(a.createdAt),<Status value={a.status}/>,canApprove&&a.status==='PENDING'?<span className="actions"><button className="small" onClick={()=>decide(a,'APPROVED')}>Approve</button><button className="small danger" onClick={()=>decide(a,'DENIED')}>Deny</button></span>:'—'])}/>{show&&<Modal title="New personnel request" close={()=>setShow(false)}><form onSubmit={submit} className="form-grid"><label>Staff member<select name="staffProfileId" required><option value="">Select</option>{staff.map(s=><option value={s.id} key={s.id}>{s.displayName}</option>)}</select></label><label>Action<select name="type" required>{['PROMOTION','DEMOTION','TRANSFER','STATUS_CHANGE','RESIGNATION','TERMINATION'].map(x=><option key={x}>{x}</option>)}</select></label><label>Current value<select name="fromValue"><option value="">None</option>{ranks.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>New value<select name="toValue"><option value="">None</option>{ranks.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}{(['ACTIVE','LEAVE_OF_ABSENCE','SUSPENDED'] as StaffStatus[]).map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Reason<textarea name="reason" rows={4} required/></label><button className="wide">Submit for review</button></form></Modal>}</section>}
const labelValue=(id:string|undefined,ranks:Rank[],departments:Department[])=>ranks.find(r=>r.id===id)?.name??departments.find(d=>d.id===id)?.name??id??'—';

function Quotas(){const {account}=useAuth();const {data:staff}=useCollectionData<StaffProfile>('staffProfiles',[orderBy('displayName')]);const {data:submissions}=useCollectionData<QuotaSubmission>('quotaSubmissions',[orderBy('createdAt','desc')]);const [show,setShow]=useState(false);const canReview=Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes('quotas.review'));
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const member=staff.find(s=>s.id===f.get('staffProfileId'));if(!member)return;await addDoc(collection(db,'quotaSubmissions'),{staffProfileId:member.id,staffName:member.displayName,activityType:clean(String(f.get('activityType'))),points:Number(f.get('points')),description:clean(String(f.get('description'))),evidenceUrl:clean(String(f.get('evidenceUrl')||'')),status:'PENDING',submittedBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}
async function decide(q:QuotaSubmission,status:'APPROVED'|'DENIED'){await runTransaction(db,async tx=>{tx.update(doc(db,'quotaSubmissions',q.id),{status,reviewedBy:auth.currentUser?.uid,reviewedAt:serverTimestamp()});if(status==='APPROVED'){const profileRef=doc(db,'staffProfiles',q.staffProfileId);const profile=await tx.get(profileRef);tx.update(profileRef,{quotaPoints:Number(profile.data()?.quotaPoints??0)+q.points,updatedAt:serverTimestamp()})}})}
return <section><SectionTitle title="Quota Management" subtitle="Submit, review, and track staff activity" action={<button onClick={()=>setShow(true)}><Plus/>Submit activity</button>}/><div className="progress-grid">{staff.filter(s=>s.status==='ACTIVE').slice(0,8).map(s=>{const target=s.quotaTarget||1;const pct=Math.min(100,Math.round(((s.quotaPoints||0)/target)*100));return <article className="progress-card" key={s.id}><div><strong>{s.displayName}</strong><span>{s.quotaPoints||0} / {s.quotaTarget||0} points</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{pct>=100?'Completed':pct>=70?'On track':'At risk'}</small></article>})}</div><SectionTitle title="Submissions" subtitle="Activity evidence awaiting review"/><DataTable headers={['Staff','Activity','Points','Evidence','Date','Status','Review']} rows={submissions.map(q=>[q.staffName,q.activityType,q.points,q.evidenceUrl?<a href={q.evidenceUrl} target="_blank">Open link</a>:'—',fmt(q.createdAt),<Status value={q.status}/>,canReview&&q.status==='PENDING'?<span className="actions"><button className="small" onClick={()=>decide(q,'APPROVED')}>Approve</button><button className="small danger" onClick={()=>decide(q,'DENIED')}>Deny</button></span>:'—'])}/>{show&&<Modal title="Submit quota activity" close={()=>setShow(false)}><form onSubmit={submit} className="form-grid"><label>Staff member<select name="staffProfileId" required><option value="">Select</option>{staff.map(s=><option value={s.id} key={s.id}>{s.displayName}</option>)}</select></label><label>Activity type<input name="activityType" required/></label><label>Points<input name="points" type="number" min="1" required/></label><label>Evidence link<input name="evidenceUrl" type="url"/></label><label className="wide">Description<textarea name="description" rows={4} required/></label><button className="wide">Submit activity</button></form></Modal>}</section>}

function Announcements(){const {account}=useAuth();const {data:ann}=useCollectionData<Announcement>('announcements',[orderBy('createdAt','desc')]);const [show,setShow]=useState(false);const canManage=Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes('announcements.manage'));
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addDoc(collection(db,'announcements'),{title:clean(String(f.get('title'))),body:clean(String(f.get('body'))),priority:String(f.get('priority')),audience:clean(String(f.get('audience'))),published:true,createdBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}
return <section><SectionTitle title="Announcements" subtitle="Targeted organization-wide communication" action={canManage?<button onClick={()=>setShow(true)}><Plus/>New announcement</button>:undefined}/><div className="announcement-list">{ann.filter(a=>a.published||canManage).map(a=><article className={`announcement ${a.priority.toLowerCase()}`} key={a.id}><div><span className="badge">{a.priority}</span><small>{a.audience} · {fmt(a.createdAt)}</small></div><h2>{a.title}</h2><p>{a.body}</p>{canManage&&<button className="small ghost-inline" onClick={()=>updateDoc(doc(db,'announcements',a.id),{published:!a.published})}>{a.published?'Unpublish':'Publish'}</button>}</article>)}</div>{show&&<Modal title="Publish announcement" close={()=>setShow(false)}><form onSubmit={create} className="form-grid"><label className="wide">Title<input name="title" required/></label><label>Priority<select name="priority"><option>NORMAL</option><option>IMPORTANT</option><option>URGENT</option></select></label><label>Audience<input name="audience" defaultValue="All Staff" required/></label><label className="wide">Message<textarea name="body" rows={7} required/></label><button className="wide">Publish announcement</button></form></Modal>}</section>}

function Admin(){const {account}=useAuth();if(!account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR'))return <Navigate to="/dashboard"/>;return <section><SectionTitle title="System Administration" subtitle="Technical access and portal configuration"/><div className="grid"><Card title="Authentication" value="Active" text="Cross-device username and password access"/><Card title="Personnel Module" value="Online" text="Staff, ranks, quotas, and workflows"/><Card title="Next Module" value="Compliance" text="Discipline, appeals, alliances, applications"/></div><div className="panel"><KeyRound/><div><h2>Account management</h2><p>Activation-code generation and full session recovery controls will connect directly to staff profiles in the final account-management expansion.</p></div></div></section>}

function SectionTitle({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}){return <div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>}
function Status({value}:{value:string}){return <span className={`status ${value.toLowerCase()}`}>{value.replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function DataTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length}><Empty text="No records yet."/></td></tr>}</tbody></table></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={close}><X/></button></div>{children}</section></div>}
function Protected(){const {user,account,loading}=useAuth();if(loading)return <div className="loading">Loading Canela Portal…</div>;if(!user||!account||account.portalStatus!=='ACTIVE')return <Navigate to="/login"/>;return <Shell/>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/activate" element={<Activate/>}/><Route path="/*" element={<Protected/>}/></Routes>}
