import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { addDoc, collection, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore';
import { AlertTriangle, Ban, FileCheck2, Handshake, Plus, Scale, X } from 'lucide-react';
import { auth, db } from './firebase';
import { useAuth } from './AuthContext';
import type { Alliance, Appeal, ApplicationRecord, BlacklistRecord, DisciplinaryCase, OffenceDefinition, StaffProfile } from './types';

const can=(account:any,p:string)=>Boolean(account?.systemRoles?.includes('SYSTEM_ADMINISTRATOR')||account?.permissions?.includes(p));
const date=(v:any)=>v?.toDate?.().toLocaleDateString()??'—';
function useDocs<T>(path:string){const [items,setItems]=useState<T[]>([]);useEffect(()=>onSnapshot(query(collection(db,path),orderBy('createdAt','desc')),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as T))),[path]);return items}
function Status({value}:{value:string}){return <span className={`status ${value.toLowerCase()}`}>{value.replaceAll('_',' ')}</span>}
function Section({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}){return <div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length}><div className="empty">No records yet.</div></td></tr>}</tbody></table></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}><X/></button></div>{children}</section></div>}

export default function PhaseThree(){const [tab,setTab]=useState<'cases'|'blacklists'|'appeals'|'alliances'|'applications'>('cases');return <section><Section title="Compliance & External Operations" subtitle="Discipline, blacklists, appeals, alliances, and applications"/><div className="tabs phase-tabs"><button className={tab==='cases'?'selected':''} onClick={()=>setTab('cases')}><AlertTriangle/>Cases</button><button className={tab==='blacklists'?'selected':''} onClick={()=>setTab('blacklists')}><Ban/>Blacklists</button><button className={tab==='appeals'?'selected':''} onClick={()=>setTab('appeals')}><Scale/>Appeals</button><button className={tab==='alliances'?'selected':''} onClick={()=>setTab('alliances')}><Handshake/>Alliances</button><button className={tab==='applications'?'selected':''} onClick={()=>setTab('applications')}><FileCheck2/>Applications</button></div>{tab==='cases'&&<Cases/>}{tab==='blacklists'&&<Blacklists/>}{tab==='appeals'&&<Appeals/>}{tab==='alliances'&&<Alliances/>}{tab==='applications'&&<Applications/>}</section>}

function Cases(){const {account}=useAuth();const staff=useDocs<StaffProfile>('staffProfiles');const offences=useDocs<OffenceDefinition>('offenceDefinitions');const cases=useDocs<DisciplinaryCase>('disciplinaryCases');const [show,setShow]=useState(false);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const member=staff.find(s=>s.id===f.get('staffProfileId'));const offence=offences.find(o=>o.id===f.get('offenceId'));if(!member||!offence)return;await addDoc(collection(db,'disciplinaryCases'),{staffProfileId:member.id,subjectName:member.displayName,offenceId:offence.id,offenceName:offence.name,occurrenceNumber:Number(f.get('occurrenceNumber')),summary:String(f.get('summary')).trim(),evidenceUrl:String(f.get('evidenceUrl')||'').trim(),recommendedAction:String(f.get('recommendedAction')||offence.firstOffenceAction).trim(),finalAction:'',status:'UNDER_REVIEW',issuedBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}async function resolve(item:DisciplinaryCase,status:'ACTIVE'|'CLOSED'){await updateDoc(doc(db,'disciplinaryCases',item.id),{status,finalAction:item.recommendedAction,resolvedBy:auth.currentUser?.uid,resolvedAt:serverTimestamp()})}return <><Section title="Disciplinary Cases" subtitle="Policy-guided case creation, evidence, and final decisions" action={can(account,'discipline.manage')?<button onClick={()=>setShow(true)}><Plus/>New case</button>:undefined}/><Table headers={['Subject','Offence','Occurrence','Recommendation','Status','Created','Action']} rows={cases.map(c=>[c.subjectName,c.offenceName,c.occurrenceNumber,c.finalAction||c.recommendedAction,<Status value={c.status}/>,date(c.createdAt),can(account,'discipline.manage')&&c.status==='UNDER_REVIEW'?<span className="actions"><button className="small" onClick={()=>resolve(c,'ACTIVE')}>Issue</button><button className="small danger" onClick={()=>resolve(c,'CLOSED')}>Close</button></span>:'—'])}/>{show&&<Modal title="Create disciplinary case" onClose={()=>setShow(false)}><form onSubmit={create} className="form-grid"><label>Subject<select name="staffProfileId" required><option value="">Select</option>{staff.map(s=><option value={s.id} key={s.id}>{s.displayName}</option>)}</select></label><label>Offence<select name="offenceId" required><option value="">Select</option>{offences.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Occurrence<input name="occurrenceNumber" type="number" min="1" defaultValue="1" required/></label><label>Recommended action<input name="recommendedAction" placeholder="Uses policy default when empty"/></label><label className="wide">Evidence link<input name="evidenceUrl" type="url"/></label><label className="wide">Case summary<textarea name="summary" rows={5} required/></label><button className="wide">Create case</button></form></Modal>}</>}

function Blacklists(){const {account}=useAuth();const items=useDocs<BlacklistRecord>('blacklists');const [show,setShow]=useState(false);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addDoc(collection(db,'blacklists'),{robloxUsername:String(f.get('robloxUsername')).trim(),robloxUserId:String(f.get('robloxUserId')).trim(),discordUsername:String(f.get('discordUsername')||'').trim(),discordId:String(f.get('discordId')||'').trim(),category:String(f.get('category')).trim(),reason:String(f.get('reason')).trim(),evidenceUrl:String(f.get('evidenceUrl')||'').trim(),permanent:f.get('permanent')==='on',appealEligible:f.get('appealEligible')==='on',status:'ACTIVE',issuedBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}return <><Section title="Blacklist Registry" subtitle="Searchable temporary and permanent restrictions" action={can(account,'blacklists.manage')?<button onClick={()=>setShow(true)}><Plus/>Add blacklist</button>:undefined}/><Table headers={['Roblox','Discord','Category','Permanent','Appeal','Status','Issued']} rows={items.map(b=>[`${b.robloxUsername} (${b.robloxUserId})`,b.discordUsername?`${b.discordUsername} (${b.discordId})`:'—',b.category,b.permanent?'Yes':'No',b.appealEligible?'Eligible':'No',<Status value={b.status}/>,date(b.createdAt)])}/>{show&&<Modal title="Create blacklist record" onClose={()=>setShow(false)}><form onSubmit={create} className="form-grid"><label>Roblox username<input name="robloxUsername" required/></label><label>Roblox User ID<input name="robloxUserId" required/></label><label>Discord username<input name="discordUsername"/></label><label>Discord ID<input name="discordId"/></label><label>Category<input name="category" required/></label><label>Evidence link<input name="evidenceUrl" type="url"/></label><label className="check"><input name="permanent" type="checkbox"/>Permanent</label><label className="check"><input name="appealEligible" type="checkbox" defaultChecked/>Appeal eligible</label><label className="wide">Reason<textarea name="reason" rows={5} required/></label><button className="wide">Create blacklist</button></form></Modal>}</>}

function Appeals(){const {account}=useAuth();const items=useDocs<Appeal>('appeals');async function decide(id:string,status:'APPROVED'|'PARTIALLY_APPROVED'|'DENIED'){await updateDoc(doc(db,'appeals',id),{status,decidedBy:auth.currentUser?.uid,decidedAt:serverTimestamp()})}return <><Section title="Appeals" subtitle="Eligibility, assignment, review, and final disposition"/><Table headers={['Appellant','Related record','Statement','Status','Submitted','Decision']} rows={items.map(a=>[a.appellantName,a.relatedRecordType,a.statement,<Status value={a.status}/>,date(a.createdAt),can(account,'appeals.review')&&!['APPROVED','PARTIALLY_APPROVED','DENIED','CLOSED'].includes(a.status)?<span className="actions"><button className="small" onClick={()=>decide(a.id,'APPROVED')}>Approve</button><button className="small" onClick={()=>decide(a.id,'PARTIALLY_APPROVED')}>Partial</button><button className="small danger" onClick={()=>decide(a.id,'DENIED')}>Deny</button></span>:'—'])}/></>}

function Alliances(){const {account}=useAuth();const items=useDocs<Alliance>('alliances');const [show,setShow]=useState(false);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addDoc(collection(db,'alliances'),{name:String(f.get('name')).trim(),robloxGroupUrl:String(f.get('robloxGroupUrl')||'').trim(),discordServer:String(f.get('discordServer')||'').trim(),canelaRepresentative:String(f.get('canelaRepresentative')).trim(),partnerRepresentative:String(f.get('partnerRepresentative')).trim(),status:'ACTIVE',strikeCount:0,notes:String(f.get('notes')||'').trim(),createdBy:auth.currentUser?.uid,createdAt:serverTimestamp()});setShow(false)}return <><Section title="Alliance Management" subtitle="Partnerships, representatives, status, strikes, and history" action={can(account,'alliances.manage')?<button onClick={()=>setShow(true)}><Plus/>New alliance</button>:undefined}/><div className="department-grid">{items.map(a=><article className="card" key={a.id}><p><Status value={a.status}/></p><strong>{a.name}</strong><span>{a.canelaRepresentative} ↔ {a.partnerRepresentative}</span><small>{a.strikeCount} strike(s)</small>{can(account,'alliances.manage')&&<button className="small ghost-inline" onClick={()=>updateDoc(doc(db,'alliances',a.id),{strikeCount:(a.strikeCount||0)+1,updatedAt:serverTimestamp()})}>Add strike</button>}</article>)}</div>{show&&<Modal title="Create alliance" onClose={()=>setShow(false)}><form onSubmit={create} className="form-grid"><label>Name<input name="name" required/></label><label>Roblox group link<input name="robloxGroupUrl" type="url"/></label><label>Discord server<input name="discordServer"/></label><label>Canela representative<input name="canelaRepresentative" required/></label><label>Partner representative<input name="partnerRepresentative" required/></label><label className="wide">Notes<textarea name="notes" rows={4}/></label><button className="wide">Create alliance</button></form></Modal>}</>}

function Applications(){const {account}=useAuth();const items=useDocs<ApplicationRecord>('applications');async function decide(id:string,status:'ACCEPTED'|'DENIED'|'WAITLISTED'){await updateDoc(doc(db,'applications',id),{status,reviewedBy:auth.currentUser?.uid,reviewedAt:serverTimestamp()})}return <><Section title="Applications & Hiring" subtitle="Screening, review, scoring, and acceptance workflows"/><Table headers={['Applicant','Type','Score','Status','Submitted','Review']} rows={items.map(a=>[a.applicantName,a.applicationType,a.score??'—',<Status value={a.status}/>,date(a.createdAt),can(account,'applications.review')&&a.status==='SUBMITTED'?<span className="actions"><button className="small" onClick={()=>decide(a.id,'ACCEPTED')}>Accept</button><button className="small" onClick={()=>decide(a.id,'WAITLISTED')}>Waitlist</button><button className="small danger" onClick={()=>decide(a.id,'DENIED')}>Deny</button></span>:'—'])}/></>}
