import type { Timestamp } from 'firebase/firestore';

export type StaffStatus = 'ACTIVE' | 'LEAVE_OF_ABSENCE' | 'SUSPENDED' | 'RESIGNED' | 'TERMINATED' | 'FORMER_STAFF';
export type ReviewStatus = 'PENDING' | 'APPROVED' | 'DENIED';

export interface StaffProfile { id:string; displayName:string; robloxUsername:string; robloxUserId:string; discordUsername:string; discordId:string; rankId:string; departmentId:string; teamId?:string; status:StaffStatus; joinedAt?:Timestamp; quotaPoints?:number; quotaTarget?:number; notes?:string; createdAt?:Timestamp; updatedAt?:Timestamp }
export interface Rank { id:string; name:string; abbreviation:string; tier:string; order:number; limit?:number; quotaTarget?:number; description?:string }
export interface Department { id:string; name:string; abbreviation:string; description?:string; active:boolean }
export interface PersonnelAction { id:string; staffProfileId:string; staffName:string; type:'PROMOTION'|'DEMOTION'|'TRANSFER'|'RESIGNATION'|'TERMINATION'|'STATUS_CHANGE'; fromValue?:string; toValue?:string; reason:string; status:ReviewStatus; requestedBy:string; approvedBy?:string; effectiveAt?:Timestamp; createdAt?:Timestamp }
export interface QuotaSubmission { id:string; staffProfileId:string; staffName:string; activityType:string; points:number; description:string; evidenceUrl?:string; status:ReviewStatus; submittedBy:string; reviewedBy?:string; createdAt?:Timestamp }
export interface Announcement { id:string; title:string; body:string; priority:'NORMAL'|'IMPORTANT'|'URGENT'; audience:string; published:boolean; createdBy:string; createdAt?:Timestamp; expiresAt?:Timestamp }

export interface OffenceDefinition { id:string; name:string; category:string; severity:string; description?:string; firstOffenceAction:string; secondOffenceAction:string; thirdOffenceAction:string; appealEligible:boolean; createdAt?:Timestamp }
export interface DisciplinaryCase { id:string; staffProfileId:string; subjectName:string; offenceId:string; offenceName:string; occurrenceNumber:number; summary:string; evidenceUrl?:string; recommendedAction:string; finalAction?:string; status:'DRAFT'|'UNDER_REVIEW'|'ACTIVE'|'APPEALED'|'OVERTURNED'|'MODIFIED'|'EXPIRED'|'CLOSED'; issuedBy:string; resolvedBy?:string; createdAt?:Timestamp; resolvedAt?:Timestamp }
export interface BlacklistRecord { id:string; robloxUsername:string; robloxUserId:string; discordUsername?:string; discordId?:string; category:string; reason:string; evidenceUrl?:string; permanent:boolean; appealEligible:boolean; status:'PENDING'|'ACTIVE'|'TEMPORARY'|'EXPIRED'|'REVOKED'|'OVERTURNED'|'ARCHIVED'; issuedBy:string; createdAt?:Timestamp }
export interface Appeal { id:string; appellantName:string; relatedRecordId:string; relatedRecordType:'DISCIPLINARY_CASE'|'BLACKLIST'|'TERMINATION'|'ALLIANCE_ACTION'|'OTHER'; statement:string; evidenceUrl?:string; status:'SUBMITTED'|'ELIGIBILITY_REVIEW'|'ASSIGNED'|'UNDER_REVIEW'|'INFORMATION_REQUESTED'|'DECISION_PENDING'|'APPROVED'|'PARTIALLY_APPROVED'|'DENIED'|'CLOSED'; assignedTo?:string; decidedBy?:string; createdAt?:Timestamp; decidedAt?:Timestamp }
export interface Alliance { id:string; name:string; robloxGroupUrl?:string; discordServer?:string; canelaRepresentative:string; partnerRepresentative:string; status:'PROSPECTIVE'|'UNDER_REVIEW'|'ACTIVE'|'PROBATION'|'INACTIVE'|'TERMINATED'|'ARCHIVED'; strikeCount:number; notes?:string; createdBy:string; createdAt?:Timestamp; updatedAt?:Timestamp }
export interface ApplicationRecord { id:string; applicantName:string; robloxUsername:string; discordUsername?:string; applicationType:string; responses?:Record<string,string>; score?:number; status:'DRAFT'|'SUBMITTED'|'SCREENING'|'INTERVIEW'|'FINAL_REVIEW'|'ACCEPTED'|'DENIED'|'WAITLISTED'|'WITHDRAWN'; reviewedBy?:string; createdAt?:Timestamp; reviewedAt?:Timestamp }
